debug: 1
# secret_key: <VAULTED>
django_allowed_hosts: dsereviews.live
sql_engine: django.db.backends.postgresql
# sql_database: <VAULTED>
# sql_user: <VAULTED>
# sql_password: <VAULTED>
sql_host: localhost
sql_port: 5432
database: postgres

# email sending hosting credentials
# email_host: <VAULTED>
# email_host_user: <VAULTED>
# email_host_password: <VAULTED>
# email_port: 587
# email_use_tls: True

# django super-user credentials
# admin_username: <VAULTED>
# admin_password: <VAULTED>
# admin_email: <VAULTED>